# $Id:$
MODULE COMP_POLY
DESCRIPTION DLM implementation of comp_poly.pro
VERSION $Revision: 0.9$
BUILD_DATE $Date: 2025/06/16 $
SOURCE S.V.H.HAUGAN
PROCEDURE COMP_POLY  3 4
PROCEDURE COMP_GAUSS  3 4
# CF_G_P0_
# CF_G_G_P0_
# CF_G_G_G_P0_
# CF_G_G_G_G_P0_
# CF_G_G_G_G_G_P0_
# CF_G_G_G_G_G_G_P0_
# CF_G_G_G_G_G_G_G_P0_
# CF_G_G_G_G_G_G_G_G_P0_
# CF_G_G_G_G_G_G_G_G_G_P0_
